
name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
        continue-on-error: true

      - name: Display test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: tests/reports

      - name: View test results in GitHub Actions
        run: |
          cat tests/reports/pytest-results.xml
